/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.pantallas;

import java.awt.Font;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import sistema.Cete;
import sistema.Sistema;

/**
 *
 * @author ALBER
 */
public class VerHistorialCetes extends javax.swing.JFrame {
    public Sistema sistem;
    private int id;
    private int quies;
    
    /**
     * Creates new form Cetes
     */
    public VerHistorialCetes(Sistema sistem, int id, int quies) {        
        initComponents();
        this.sistem = sistem;
        this.id = id;
        this.quies = quies;
        Despliega();
    }
    
    public void Despliega(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[9];
        Iterator itr = sistem.getHistorialCetes().iterator();
        while(itr.hasNext()){
            Cete cet = (Cete) itr.next();
            //System.out.println(promo.getNombre() + "    " + promo.getContra() );
            if( quies == 3){
                rowData[0] = cet.getId();
                rowData[1] = cet.getIdCliente();
                rowData[2] = cet.getValorNominal();
                rowData[3] = cet.getPlazo();
                rowData[4] = cet.getTasaFija();
                rowData[5] = cet.isReinversion();
                rowData[6] = cet.getDiasTranscurridos();
                rowData[7] = cet.getComisionPromotor();
                rowData[8] = cet.getComisionCasa();
                model.addRow(rowData);
            }
            else if( cet.getIdPromotor() == id && quies == 1 ){
                rowData[0] = cet.getId();
                rowData[1] = cet.getIdCliente();
                rowData[2] = cet.getValorNominal();
                rowData[3] = cet.getPlazo();
                rowData[4] = cet.getTasaFija();
                rowData[5] = cet.isReinversion();
                rowData[6] = cet.getDiasTranscurridos();
                rowData[7] = cet.getComisionPromotor();
                rowData[8] = cet.getComisionCasa();
                model.addRow(rowData);
            }
            else if( cet.getIdCliente() == id && quies == 2 ){
                rowData[0] = cet.getId();
                rowData[1] = cet.getIdCliente();
                rowData[2] = cet.getValorNominal();
                rowData[3] = cet.getPlazo();
                rowData[4] = cet.getTasaFija();
                rowData[5] = cet.isReinversion();
                rowData[6] = cet.getDiasTranscurridos();
                rowData[7] = cet.getComisionPromotor();
                rowData[8] = cet.getComisionCasa();
                model.addRow(rowData);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cetes");
        jLabel1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdInversion", "IdCliente", "Valor", "Plazo", "Tasa", "Reinversion", "Dias Transcurridos", "Comision Promotor", "Comision Casa"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ( quies == 1 ){
            MainPromotor MP = new MainPromotor(sistem , id );
            MP.setVisible(true);
            dispose();
        }
        if (quies == 2){
            MainCliente MC = new MainCliente(sistem, id);
            MC.setVisible(true);
            dispose();
        }
        if (quies == 3){
            MainDirector MD = new MainDirector(sistem);
            MD.setVisible(true);
            dispose();
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
